# Generated by Django 3.1.7 on 2021-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'Седан'), (2, 'Хэтчбек'), (3, 'Универсал'), (4, 'Купе')], verbose_name='Тип кузова'),
        ),
    ]
